// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WeatherRepository;

#nullable disable

namespace WeatherRepository.Migrations
{
    [DbContext(typeof(WeatherContext))]
    partial class WeatherContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WeatherApiDomain.Entity.CityEntity", b =>
                {
                    b.Property<Guid>("IdCity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdCity");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CityEntities");
                });

            modelBuilder.Entity("WeatherApiDomain.Entity.WeatherForecast", b =>
                {
                    b.Property<Guid>("IdWeather")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayTimeEnum")
                        .HasColumnType("integer");

                    b.Property<int>("Humidity")
                        .HasColumnType("integer");

                    b.Property<int>("MaxTemperature")
                        .HasColumnType("integer");

                    b.Property<int>("MinTemperature")
                        .HasColumnType("integer");

                    b.Property<int>("NightTimeEnum")
                        .HasColumnType("integer");

                    b.Property<int>("Precipitation")
                        .HasColumnType("integer");

                    b.Property<int>("WindSpeed")
                        .HasColumnType("integer");

                    b.HasKey("IdWeather");

                    b.HasIndex("CityId");

                    b.ToTable("WeatherDataEntities");
                });

            modelBuilder.Entity("WeatherApiDomain.Entity.WeatherForecast", b =>
                {
                    b.HasOne("WeatherApiDomain.Entity.CityEntity", "City")
                        .WithMany("WeatherForecastList")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("WeatherApiDomain.Entity.CityEntity", b =>
                {
                    b.Navigation("WeatherForecastList");
                });
#pragma warning restore 612, 618
        }
    }
}
